services:
  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.home.arpa`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
        - lan

networks:
  lan:
    external: true
