apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
spec:
  interval: 5m
  chart:
    spec:
      version: "2.x"
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: mojo2600
      interval: 60m
  valuesFrom:
    - kind: ConfigMap
      name: pihole-configmap
