services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    volumes:
      - /var/lib/homeassistant:/config # Mount Nix-managed host directory for HA data
      - /etc/homeassistant/configuration.yaml:/config/configuration.yaml:ro # Mount specific Nix config file read-only
    environment:
      - TZ=Europe/Berlin
    network_mode: "host"
