# immich-compose.yml
# Make sure to replace placeholder secrets before use!

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    # command: [ "start.sh", "immich" ] # Default command
    volumes:
      - immich_upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_HOSTNAME=immich_postgres
      - DB_USERNAME=immich
      - DB_PASSWORD=changeme_immich_db_password # --- CHANGE THIS ---
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immich_redis
      - JWT_SECRET=changeme_immich_jwt_secret # --- CHANGE THIS ---
      - IMMICH_MACHINE_LEARNING_URL=http://immich_machine_learning:3003
      - TZ=Europe/Berlin
    depends_on:
      - immich_redis
      - immich_postgres
    restart: always
    networks:
      - immich_internal
      - proxy # Connect to Traefik network
    labels:
      traefik.enable: "true"
      # Define the main HTTPS router for Immich
      traefik.http.routers.immich-secure.entrypoints: "websecure"
      traefik.http.routers.immich-secure.rule: "Host(`photos.blokth.com`)"
      traefik.http.routers.immich-secure.tls: "true"
      traefik.http.routers.immich-secure.service: "immich-service"
      # Define the service (points to the container)
      traefik.http.services.immich-service.loadbalancer.server.port: "3001" # Immich server port

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "microservices" ]
    volumes:
      - immich_upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_HOSTNAME=immich_postgres
      - DB_USERNAME=immich
      - DB_PASSWORD=changeme_immich_db_password # --- CHANGE THIS ---
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immich_redis
      - IMMICH_MACHINE_LEARNING_URL=http://immich_machine_learning:3003
      - TZ=Europe/Berlin
    depends_on:
      - immich_redis
      - immich_postgres
    restart: always
    networks:
      - immich_internal

  immich-machine-learning:
    container_name: immich_machine_learning
    # Use the ML image
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - immich_ml_models:/cache
    environment:
      - DB_HOSTNAME=immich_postgres
      - DB_USERNAME=immich
      - DB_PASSWORD=changeme_immich_db_password # --- CHANGE THIS ---
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immich_redis
      - TZ=Europe/Berlin
    restart: always
    networks:
      - immich_internal

  immich_redis:
    container_name: immich_redis
    image: redis:7.4-alpine
    restart: always
    networks:
      - immich_internal
    volumes:
      - immich_redis_data:/data

  immich_postgres:
    container_name: immich_postgres
    image: tensorchord/pgvecto.rs:pg16
    environment:
      - POSTGRES_USER=immich
      - POSTGRES_PASSWORD=changeme_immich_db_password # --- CHANGE THIS ---
      - POSTGRES_DB=immich
    volumes:
      - immich_pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - immich_internal

volumes:
  immich_upload:
  immich_ml_models:
  immich_redis_data:
  immich_pgdata:

networks:
  immich_internal:
    driver: bridge
  proxy:
    external: true 