services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports (Keep these exposed for DNS resolution)
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port (Comment out - Traefik handles this)
      # - "80:80/tcp"
      # Default HTTPs Port (Comment out - Traefik handles this)
      # - "443:443/tcp"
      # Uncomment the line below if you are using Pi-hole as your DHCP server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    # Explicitly set DNS servers for the container itself
    dns:
      - "1.1.1.1"
      - "1.0.0.1"
    environment:
      TZ: 'Europe/Berlin' # Keep user's timezone
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: 'changeme' # Using new v6 variable name. Change the password!
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: 'all' # Using new v6 variable name
      # Upstream DNS servers (Pi-hole will use these to forward client requests)
      FTLCONF_dns_upstreams: "1.1.1.1;1.0.0.1" # Using new v6 variable name, kept user's servers
      # Tell FTL to load configs from /etc/dnsmasq.d/
      FTLCONF_misc_etc_dnsmasq_d: 'true'
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - './etc-pihole:/etc/pihole'
      # Mount dnsmasq.d directory from host
      - /etc/dnsmasq.d:/etc/dnsmasq.d:ro
      # Remove custom list volume mount
      # - /etc/pihole/custom.list:/etc/pihole/custom.list
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d' # Commented out per guide's fresh start recommendation
    networks:
      proxy: # Keep user's network choice for Traefik
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    labels:
      # Keep user's Traefik labels
      traefik.enable: "true"
      traefik.http.routers.pihole-http.entrypoints: "http"
      traefik.http.routers.pihole-http.rule: "Host(`pihole.blokth.com`)"
      traefik.http.services.pihole-service.loadbalancer.server.port: "80"
    restart: unless-stopped

networks:
  proxy:
    external: true
