services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'Europe/Berlin'
      # !!! CHANGE THIS PASSWORD !!! Use a strong, unique password
      WEBPASSWORD: 'changeme'
      PIHOLE_DNS_: "1.1.1.1;1.0.0.1"
      DNSMASQ_LISTENING: "all"
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
      - /etc/pihole/custom.list:/etc/pihole/custom.list
    networks:
      traefik-public:
      pihole_net:
        ipv4_address: 192.168.88.192
    cap_add:
        - NET_ADMIN
    labels:
      traefik.enable: "true"
      traefik.http.routers.pihole-http.entrypoints: "http"
      traefik.http.routers.pihole-http.rule: "Host(`pihole.blokth.com`)"
      traefik.http.services.pihole-service.loadbalancer.server.port: "80"

networks:
  traefik-public:
    external: true
  pihole_net:
    driver: macvlan
    driver_opts:
      parent: eno1
    ipam:
      config:
        - subnet: 192.168.88.0/24
          ip_range: 192.168.88.192/26
