services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "192.168.88.192:53:53/tcp"
      - "192.168.88.192:53:53/udp"
      - "192.168.88.192:80:80"
      - "192.168.88.192:443:443"
    environment:
      TZ: 'Europe/Berlin'
      # !!! CHANGE THIS PASSWORD !!! Use a strong, unique password
      WEBPASSWORD: 'changeme'
      PIHOLE_DNS_: "1.1.1.1;1.0.0.1"
      FTLCONF_LOCAL_IPV4: "192.168.88.192"
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
      - /etc/pihole/custom.list:/etc/pihole/custom.list
    mac_address: '02:42:ac:11:00:02' 
    networks:
      pihole_network:
        ipv4_address: '192.168.88.192' # !!! MATCH FTLCONF_LOCAL_IPV4 !!!
      traefik-public:
    labels:
      traefik.enable: "true"
      traefik.http.routers.pihole-http.entrypoints: "http"
      traefik.http.routers.pihole-http.rule: "Host(`pihole.blokth.com`)"
      traefik.http.services.pihole-service.loadbalancer.server.port: "80"

networks:
  pihole_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.88.0/24"
  traefik-public:
    external: true
