services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'Europe/Berlin'
      # !!! CHANGE THIS PASSWORD !!! Use a strong, unique password
      WEBPASSWORD: 'changeme'
      PIHOLE_DNS_: "1.1.1.1;1.0.0.1"
      FTLCONF_LOCAL_IPV4: "192.168.88.189"
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
      - /etc/pihole/custom.list:/etc/pihole/custom.list
    mac_address: '02:42:ac:11:00:02' 
    networks:
      traefik-public:
    labels:
      traefik.enable: "true"
      traefik.http.routers.pihole-http.entrypoints: "http"
      traefik.http.routers.pihole-http.rule: "Host(`pihole.blokth.com`)"
      traefik.http.services.pihole-service.loadbalancer.server.port: "80"

networks:
  traefik-public:
    external: true
