apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 5m
  chart:
    spec:
      version: "1.x"
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
      interval: 60m
