permit_join: true
homeassistant: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt
serial:
  port: /dev/ttyUSB0
  adapter: ember
frontend:
  url: https://zigbee.def4alt.com
  port: 8080
advanced:
  network_key:
    - 171
    - 218
    - 13
    - 69
    - 9
    - 160
    - 70
    - 174
    - 66
    - 104
    - 174
    - 209
    - 5
    - 252
    - 182
    - 100
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
devices:
  '0x001788010e1ba8c5':
    friendly_name: bed lamp
  '0x0c2a6ffffe45ba25':
    friendly_name: corner lamp
