---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
resources:
  - namespace.yaml
  - repository.yaml
  - release/kustomization.yaml
  - configs/kustomization.yaml
