---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 5m
  path: "./infrastructure/metallb/controller"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: metallb
      namespace: metallb-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pools
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb
  interval: 5m
  path: "./infrastructure/metallb/pools"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
