---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: immich
      interval: 12h
  values:
    immich:
      persistence:
        library:
          existingClaim: immich-pvc
    server:
      enabled: true
      ingress:
        main:
          enabled: true
          annotations:
            # proxy-body-size is set to 0 to remove the body limit on file uploads
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
          hosts:
            - host: immich.def4alt.com
              paths:
                - path: "/"
          tls: []

    machine-learning:
      enabled: true
      image:
        repository: ghcr.io/immich-app/immich-machine-learning
        pullPolicy: IfNotPresent
      env:
        TRANSFORMERS_CACHE: /cache
      persistence:
        cache:
          enabled: true
          size: 10Gi
          # Optional: Set this to pvc to avoid downloading the ML models every start.
          type: emptyDir
          accessMode: ReadWriteMany
          storageClass: longhorn
