---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 5m
  path: "./infrastructure/traefik/controller"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: traefik
      namespace: traefik-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tlsstore
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik
  interval: 5m
  path: "./infrastructure/traefik/tlsstores"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
