---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "v34.x"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    ingressClass:
      name: traefik
      isDefaultClass: true
    providers:
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: true
    ports:
      mqtt:
        port: 1883
        exposedPort: 1883
        expose:
          default: true
