---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "v34.x"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    ingressClass: traefik
    additionalArguments:
      - "--providers.kubernetesingress.ingressclass=traefik"
    service:
      type: LoadBalancer
    ports:
      web:
        port: 80
        expose: true
      websecure:
        port: 443
        expose: true
