services:
  traefik:
    image: "traefik:v3.2"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.network=lan"  # replace with your configured Docker network name
      - "--entrypoints.web.address=:80"
      - "--entrypoints.mqtt.address=:1883"
      - "--entrypoints.mqtts.address=:8883"
    ports:
      - "80:80"
      - "8883:8883"
      - "1883:1883"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - lan
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.def4alt.com`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=web"

networks:
  lan:
    external: true
