services:
  traefik:
    image: "traefik:v3.2"
    container_name: "traefik"
    command:
      - "--providers.docker=true"
      - "--providers.docker.network=lan"  # replace with your configured Docker network name
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - lan

networks:
  lan:
    external: true
