services:
  homeassistant:
    container_name: home-assistant
    restart: always
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Berlin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://192.168.88.189:8123"] #host
      interval: "30s"
      timeout: "10s"
      retries: "10"
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
      - SYS_ADMIN
    network_mode: "host"
    extra_hosts:
      - "mqtt:172.19.0.10"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.home-assistant.loadbalancer.server.port=8123"
      - "traefik.http.routers.home-assistant.rule=Host(`home-assistant.home.arpa`)"
      - "traefik.http.routers.home-assistant.entrypoints=web"
    image: homeassistant/home-assistant:latest
