---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: external-dns
  namespace: pihole-system
spec:
  interval: 24h
  url: oci://registry-1.docker.io/bitnamicharts/external-dns
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: externaldns-pihole
  namespace: pihole-system
spec:
  dependsOn:
    - name: pihole
  interval: 30m
  sourceRef:
    kind: OCIRepository
    name: external-dns
    namespace: pihole-system
  values:
    provider: pihole
    policy: upsert-only
    txtOwnerId: "homelab"
    pihole:
      server: http://pihole-web.pihole-system.svc.cluster.local
    extraEnvVars:
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pihole-password
            key: password
    serviceAccount:
      create: true
      name: "external-dns"
    ingressClassFilters:
      - nginx-internal
