---
apiVersion: v1
kind: Namespace
metadata:
  name: zigbee2mqtt
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: truecharts
  namespace: zigbee2mqtt
spec:
  interval: 24h
  type: oci
  url: oci://tccr.io/truecharts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mqtt
  namespace: zigbee2mqtt
spec:
  interval: 30m
  chart:
    spec:
      chart: mosquitto
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: truecharts
      interval: 12h
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mqtt
  namespace: zigbee2mqtt
spec:
  entryPoints:
    - mqtt
  routes:
  - kind: Rule
    match: HostSNI(`*`)
    services:
    - kind: Service
      name: mqtt
      namespace: zigbee2mqtt
      port: 1883
