---
apiVersion: v1
kind: Namespace
metadata:
  name: pihole-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mojo2600
  namespace: pihole-system
spec:
  interval: 24h
  url: https://mojo2600.github.io/pihole-kubernetes
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole-system
spec:
  interval: 30m
  chart:
    spec:
      chart: mojo2600/pihole
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: pihole-system
      interval: 12h
  values:
    DNS1:
      192.168.88.189
    persistantVolumeClaim:
      enabled: true
    ingress:
      enabled: true
      hosts:
        - "pihole.home"
    serviceWeb:
      loadBalancerIP: 192.168.88.250
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    serviceDns:
      loadBalancerIP: 192.168.88.250
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    replicaCount: 1
