---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 24h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:

piVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 12h
  values:
    deployment:
      enabled: true
    service:
      enabled: true
      type: LoadBalancer
      ports:
        web:
          port: 80
        mqtt:
          port: 1883
        mqtts:
          port: 8883
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.home`)
        entryPoints:
          - web
    entryPoints:
      web:
        address: ":80"
      mqtt:
        address: ":1883"
      mqtts:
        address: ":8883"
    providers:
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: true
    ports:
      web:
        expose: true
        port: 80
      mqtt:
        expose: true
        port: 1883
      mqtts:
        expose: true
        port: 8883
    logs:
      general:
        level: INFO
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: "traefik-internal"
