---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
    name: zigbee2mqtt
    namespace: zigbee2mqtt
spec:
    interval: 10m
    url: https://charts.zigbee2mqtt.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
    name: zigbee2mqtt
    namespace: zigbee2mqtt
spec:
    interval: 5m
    dependsOn:
      - name: mqtt
    targetNamespace: zigbee2mqtt
    chart:
      spec:
        chart: zigbee2mqtt
        version: '*'
        sourceRef:
          kind: HelmRepository
          name: zigbee2mqtt
          namespace: zigbee2mqtt
        interval: 10m
    values:
      ingress:
        enabled: true
        ingressClassName: "traefik"
        hosts:
          - host: zigbee.home
            paths:
              - path: /
                pathType: ImplementationSpecific
              - path: /api
                pathType: ImplementationSpecific
      statefulset:
        storage:
          enabled: true
          storageClassName: longhorn
      service:
        port: 80
      zigbee2mqtt:
        mqtt:
          server: mqtt://mqtt
        serial:
          port: /dev/ttyUSB0
          adapter: ember
        frontend:
          port: 8080
          url: zigbee.home
        advanced:
          network_key: GENERATE
