---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: externaldns-pihole
  namespace: pihole
spec:
  dependsOn:
    - name: pihole
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 12h
  values:
    provider: pihole
    policy: upsert-only
    txtOwnerId: "homelab"
    pihole:
      server: http://pihole-web.pihole-system.svc.cluster.local
    extraEnvVars:
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pihole-password
            key: password
    serviceAccount:
      create: true
      name: "external-dns"
    ingressClassFilters:
      - traefik
