---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-controller
  namespace: cert-manager
spec:
  resources:
    - ./repository.yaml
    - ./release.yaml
