---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 30m
  chart:
    spec:
      chart: pihole
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: pihole
      interval: 12h
  values:
    DNS1:
      192.168.88.189
    persistantVolumeClaim:
      enabled: true
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - "pihole.home"
    serviceWeb:
      loadBalancerIP: 192.168.88.250
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    serviceDns:
      loadBalancerIP: 192.168.88.250
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    replicaCount: 1
