---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: metallb-controller
  namespace: metallb-system
spec:
  resources:
    - ./repository.yaml
    - ./release.yaml
