---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-configs
  namespace: cert-manager
spec:
  dependsOn:
    - cert-manager
resources:
  - clusterissuer-prod.yaml
