---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Use the Let’s Encrypt production ACME server:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: andrii.olkhovych@pm.me
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: traefik

