apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik-system
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - cluster-issuers.yaml
  - certificate.yaml
