apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  releaseName: home-assistant
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: pajikos
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: home.home
          paths:
            - path: /
              pathType: ImplementationSpecific
    persistence:
      enabled: true
      storageClass: "longhorn"
