---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-certs
  namespace: cert-manager
spec:
  resources:
    - ./default.yaml
  dependsOn:
    - name: cert-manager-issuers
