services:
  mqtt:
      container_name: mqtt
      image: eclipse-mosquitto:2.0
      restart: unless-stopped
      volumes:
          - './mosquitto-data:/mosquitto'
      networks:
        lan:
          ipv4_address: 172.19.0.10
      command: 'mosquitto -c /mosquitto-no-auth.conf'
      labels:
        - "traefik.enable=true"
        - "traefik.tcp.routers.mosquitto-MQTT.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.mosquitto-MQTT.entrypoints=mqtt"

  zigbee2mqtt:
      container_name: zigbee2mqtt
      restart: unless-stopped
      image: koenkk/zigbee2mqtt
      networks:
        lan:
          ipv4_address: 172.19.0.11
      volumes:
        - ./zigbee2mqtt-data:/app/data
        - /run/udev:/run/udev:ro
      environment:
        - TZ=Europe/Berlin
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.zigbee2mqtt.loadbalancer.server.port=8080"
        - "traefik.http.routers.zigbee2mqtt.rule=Host(`zigbee.home.arpa`)"
        - "traefik.http.routers.zigbee2mqtt.entrypoints=web"
      devices:
          - /dev/ttyUSB0:/dev/ttyUSB0
      depends_on:
        - mqtt

networks:
  lan:
    external: true
