# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."zigbee2mqtt" = {
    image = "koenkk/zigbee2mqtt";
    environment = {
      "TZ" = "Europe/Berlin";
    };
    volumes = [
      "/Users/andrii/homelab/services/zigbee2mqtt/zigbee2mqtt-data:/app/data:rw"
      "/run/udev:/run/udev:ro"
    ];
    labels = {
      "traefik.enable" = "true";
      "traefik.http.routers.zigbee2mqtt.entrypoints" = "web";
      "traefik.http.routers.zigbee2mqtt.rule" = "Host(`zigbee.home.arpa`)";
      "traefik.http.services.zigbee2mqtt.loadbalancer.server.port" = "8080";
    };
    dependsOn = [
      "zigbee2mqtt-mqtt"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=/dev/ttyUSB0:/dev/ttyUSB0:rwm"
      "--ip=172.21.0.4"
      "--network-alias=zigbee2mqtt"
      "--network=lan"
    ];
  };
  systemd.services."docker-zigbee2mqtt" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-zigbee2mqtt-root.target"
    ];
    wantedBy = [
      "docker-compose-zigbee2mqtt-root.target"
    ];
  };
  virtualisation.oci-containers.containers."zigbee2mqtt-mqtt" = {
    image = "eclipse-mosquitto:2.0";
    volumes = [
      "/Users/andrii/homelab/services/zigbee2mqtt/mosquitto-data:/mosquitto:rw"
    ];
    cmd = [ "mosquitto" "-c" "/mosquitto-no-auth.conf" ];
    log-driver = "journald";
    extraOptions = [
      "--ip=172.21.0.2"
      "--network-alias=mqtt"
      "--network=lan"
    ];
  };
  systemd.services."docker-zigbee2mqtt-mqtt" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-zigbee2mqtt-root.target"
    ];
    wantedBy = [
      "docker-compose-zigbee2mqtt-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-zigbee2mqtt-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
