---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mqtt
  namespace: zigbee2mqtt
spec:
  interval: 30m
  chart:
    spec:
      chart: mosquitto
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: truecharts
      interval: 12h
