services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    dns:
      - 127.0.0.1
      - 9.9.9.9
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'PASSWORD'
      PIHOLE_DNS_: 9.9.9.9;149.112.112.112;1.1.1.1
      DNSSEC: 'true'
      ServerIP: 192.168.88.189 # Actual server IP. Matches DHCP conf file IP
      VIRTUAL_HOST: pihole.home # Same as port traefik config
      DNSMASQ_LISTENING: all
      DHCP_ACTIVE: 'true'
      DHCP_START: 192.168.88.192
      DHCP_END: 192.168.88.255
      DHCP_ROUTER: 192.168.88.1
      DHCP_LEASETIME: 6
      WEBTHEME: default-dark
      PIHOLE_DOMAIN: lan
    volumes:
      - '/services/pihole/pihole:/etc/pihole/'
      - '/services/pihole/dnsmasq.d:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks: 
      lan: {}
      backend:
        ipv4_address: '172.31.0.100'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.home`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole.entrypoints=web"
    depends_on:
      - dhcphelper

  dhcphelper:
    image: homeall/dhcphelper:latest
    container_name: dhcphelper
    restart: unless-stopped
    network_mode: "host"
    environment:
      IP: '172.31.0.100'
      TZ: 'Europe/Berlin'
    cap_add:
      - NET_ADMIN

networks: 
  backend:
    ipam:
      config:
        - subnet: 172.31.0.0/16
  lan:
    external: true
