---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
spec:
  interval: 30m
  chart:
    spec:
      chart: paperless-ngx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: gabe565
      interval: 12h
  values:
    ingress:
      main:
        enabled: true
        hosts:
          - host: paperless.home
            paths:
              - path: /
    persistance:
      data:
        enabled: true
        storageClass: "longhorn"
        size: 5Gi
      media:
        enabled: true
        storageClass: "longhorn"
        size: 8Gi
    postgresql:
      enabled: true
      primary:
        persistance:
          enabled: true
          storageClass: "longhorn"
          size: 8Gi
