---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
spec:
  interval: 30m
  chart:
    spec:
      chart: paperless-ngx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: gabe565
      interval: 12h
  values:
    env:
      PAPERLESS_ADMIN_USER: def4alt
      PAPERLESS_ADMIN_PASSWORD: changeme
    ingress:
      main:
        enabled: true
        hosts:
          - host: papers.def4alt.com
            paths:
              - path: /
    persistence:
      data:
        enabled: true
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 5Gi
      media:
        enabled: true
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 8Gi
      export:
        enabled: true
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 1Gi
      consume:
        enabled: true
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 4Gi
    postgresql:
      enabled: true
      primary:
        persistence:
          enabled: true
          storageClass: "longhorn"
          size: 8Gi
