---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gabe565
  namespace: paperless-ngx
spec:
  interval: 24h
  type: oci
  url: oci://ghcr.io/gabe565/charts/paperless-ngx
