---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: "2025-02-09T11:30:36Z"
  name: secret
  namespace: default
  resourceVersion: "3231"
  uid: 2d926814-1d45-40be-897b-130290def6fc
type: Opaque
